Feature DO-97
QuiNovas/terraform-aws-guardduty pull request #1
Opened 2018-09-11 10:58 UTC by vchinnakotla

2018-09-26 19:35 UTC, joseph-wortmann commented
Fill in the description on all variables and outputs

2018-09-26 19:36 UTC, joseph-wortmann requested changes
I made some organizational changes. You need to fill in the description on all variables and outputs.

2018-09-27 09:52 UTC, vchinnakotla commented
added the description to all variables, please review.

2018-10-03 18:47 UTC, joseph-wortmann approved these changes

2018-10-03 18:47 UTC, merged